services:
  loadbalancer:
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=clients
    depends_on:
      - postgres
    volumes:
      - ./config.json:/lb/config.json
    networks:
      - lb-network
    init: true

  postgres:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=clients
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./internal/database/postgresql/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    networks:
      - lb-network

networks:
  lb-network:
    driver: bridge

volumes:
  pgdata: